### ISSUE TITLE
Enable auto update of github actions.

### ISSUE THREAD

**Issue by VolkerHartmann** [kit-data-manager/collection-api#81]
**Is your feature request related to a problem? Please describe.**
It is tedious to keep the githubActions versions up to date.
This can also be done by dependabot.

**Describe the solution you'd like**
Add the following lines to 'dependabot.yml':
```
  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "development"
    schedule:
      interval: "weekly"
```
